databases:
  - name: hospital-management-mongodb
    databaseName: hospital-management
    user: hospital-user
    plan: free

services:
  # Backend API Service
  - type: web
    name: hospital-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: hospital-management-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: "7d"
      - key: COOKIE_EXPIRE
        value: "7"
      - key: CORS_ORIGIN
        value: https://hospital-frontend.onrender.com
    healthCheckPath: /api/v1/health
    autoDeploy: true
    pullRequestPreviewsEnabled: true

  # Frontend Service
  - type: web
    name: hospital-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hospital-backend.onrender.com
    autoDeploy: true
    pullRequestPreviewsEnabled: true

  # Dashboard Service
  - type: web
    name: hospital-dashboard
    env: static
    plan: free
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: ./dashboard/dist
    envVars:
      - key: VITE_API_URL
        value: https://hospital-backend.onrender.com
    autoDeploy: true
    pullRequestPreviewsEnabled: true 