services:
  # Backend API Service (now serves frontend and dashboard too)
  - type: web
    name: lifecare-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: "4000"
      - key: MONGO_URI
        value: "mongodb+srv://HOSPITAL:HOSPITAL@cluster0.rh1efpz.mongodb.net/?retryWrites=true"
      - key: FRONTEND_URL
        value: "https://lifecare-backend.onrender.com"
      - key: DASHBOARD_URL
        value: "https://lifecare-backend.onrender.com/dashboard"
      - key: JWT_SECRET_KEY
        value: "asjhdkj3hkjd1fhksahfksad"
      - key: JWT_EXPIRES
        value: "7d"
      - key: COOKIE_EXPIRE
        value: "7"
      - key: CLOUDINARY_CLOUD_NAME
        value: "ddmlxju8j"
      - key: CLOUDINARY_API_SECRET
        value: "pPURipHJig0iBNcUbiJgBnZzvpg"
      - key: CLOUDINARY_API_KEY
        value: "465373931988997"
    healthCheckPath: /api/v1/health
    autoDeploy: true
    pullRequestPreviewsEnabled: true 