services:
  # Backend API Service
  - type: web
    name: hospital-backend
    env: node
    plan: free
    buildCommand: npm run build:backend
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: "4000"
      - key: MONGO_URI
        value: "mongodb+srv://HOSPITAL:HOSPITAL@cluster0.rh1efpz.mongodb.net/?retryWrites=true"
      - key: FRONTEND_URL
        value: "https://hospital-frontend.onrender.com"
      - key: DASHBOARD_URL
        value: "https://hospital-dashboard.onrender.com"
      - key: JWT_SECRET_KEY
        value: "asjhdkj3hkjd1fhksahfksad"
      - key: JWT_EXPIRES
        value: "7d"
      - key: COOKIE_EXPIRE
        value: "7"
      - key: CLOUDINARY_CLOUD_NAME
        value: "ddmlxju8j"
      - key: CLOUDINARY_API_SECRET
        value: "pPURipHJig0iBNcUbiJgBnZzvpg"
      - key: CLOUDINARY_API_KEY
        value: "465373931988997"
    healthCheckPath: /api/v1/health
    autoDeploy: true
    pullRequestPreviewsEnabled: true

  # Frontend Service
  - type: web
    name: hospital-frontend
    env: static
    plan: free
    buildCommand: npm run build:frontend
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hospital-backend.onrender.com
      - key: VITE_DASHBOARD_URL
        value: https://hospital-dashboard.onrender.com
    autoDeploy: true
    pullRequestPreviewsEnabled: true

  # Dashboard Service
  - type: web
    name: hospital-dashboard
    env: static
    plan: free
    buildCommand: npm run build:dashboard
    staticPublishPath: ./dashboard/dist
    envVars:
      - key: VITE_API_URL
        value: https://hospital-backend.onrender.com
      - key: VITE_DASHBOARD_URL
        value: https://hospital-dashboard.onrender.com
    autoDeploy: true
    pullRequestPreviewsEnabled: true 